#include <atomic>
#include <mutex>
#include <condition_variable>
#include <queue>

#include "event_loop.h"

struct EventRecord
{
    EventLoop::Handler handler;
    EventLoop::Timestamp expiration;
};

using EventQueue = std::queue<EventRecord>;

//------------------------------------------------------------------------------

struct EventLoop::Impl
{
    // Default sleep time for idle event loop.
    static constexpr long DefaultSleepMs = 200;

    EventQueue queue;
    std::atomic<bool> running{ true };
    int exitCode{ 0 };

    std::mutex mutex;
    std::condition_variable wait;

    Impl()
    {
        running = true;
    }

    void enqueue(EventLoop::Handler handler, const EventLoop::Timestamp& expiration)
    {
        EventRecord event{ std::move(handler), expiration };

        // Add event to the queue and notify the loop
        std::unique_lock<std::mutex> lock(mutex);
        queue.push(event);
        wait.notify_all();
    }

    /**
     * Process all pending events.
     *
     * This method will process all the events currently in the queue.
     * Events, which are not yet expired will be re-enqueued to be processed later.
     * The method will compute the minimal wait time to the next expected
     * call for the events processing.
     *
     * @return Time (in ms) to wait till the next call of this method.
     */
    long processEvents()
    {
        EventLoop::Timestamp now{ std::chrono::steady_clock::now() };
        auto sleepTime{ DefaultSleepMs };

        // Swap active queue with an empty one to avoid mixing with
        // events generated by handlers calls.
        EventQueue activeQueue;
        mutex.lock();
        activeQueue.swap(queue);
        mutex.unlock();

        while (!activeQueue.empty()) {
            const EventRecord &event{ activeQueue.front() };

            if (now >= event.expiration) {
                event.handler();
                // Abort sleep if at least one event gets processed
                sleepTime = 0;
            } else {
                if (sleepTime > 0) {
                    // Find the minimal sleep time among all suspended events
                    const long eventSleep{ (long)std::chrono::duration_cast<std::chrono::milliseconds>(event.expiration - now).count() };

                    if (eventSleep < sleepTime) sleepTime = eventSleep;
                }

                // Re-enqueue suspended event
                mutex.lock();
                queue.push(event);
                mutex.unlock();
            }

            activeQueue.pop();
        }

        return sleepTime;
    }

    /**
     * Run the event loop.
     *
     * This method will run the event loop until terminated via quit() method.
     *
     * @return Exit code.
     */
    int exec()
    {
        running = true;

        std::mutex waitMutex;

        while (running) {
            const long sleep_ms{ processEvents() };

            if (sleep_ms > 0) {
                std::unique_lock<std::mutex> lock(waitMutex);
                wait.wait_for(lock, std::chrono::milliseconds(sleep_ms));
            }
        }

        return exitCode;
    }

    /**
     * Quit the event loop.
     *
     * @param code Exit code to be returned by exit() method.
     */
    void quit(int code = 0)
    {
        std::unique_lock<std::mutex> lock(mutex);
        exitCode = code;
        running = false;
        wait.notify_all();
    }

};

//------------------------------------------------------------------------------

EventLoop::EventLoop()
    : d{ std::make_unique<Impl>() }
{
}

EventLoop::EventLoop(EventLoop&& other)
    : d{ std::move(other.d) }
{
}

EventLoop::~EventLoop() = default;

int EventLoop::exec()
{
    return d->exec();
}

void EventLoop::quit(int code)
{
    d->quit(code);
}

void EventLoop::processEventsAndQuit(int code)
{
    d->enqueue([this, code] { this->quit(code); }, std::chrono::steady_clock::now());
}

void EventLoop::processEvents()
{
    d->processEvents();
}

void EventLoop::emit(Handler handler)
{
    d->enqueue(std::move(handler), std::chrono::steady_clock::now());
}

void EventLoop::emitDelayed(Handler handler, long delayMs)
{
    const auto now{ std::chrono::steady_clock::now() };
    const auto expiration{ now + std::chrono::milliseconds(delayMs) };
    d->enqueue(std::move(handler), expiration);
}

void EventLoop::emitOnTime(Handler handler, const Timestamp &ts)
{
    d->enqueue(std::move(handler), ts);
}

bool EventLoop::isRunning() const
{
    return d->running;
}

int EventLoop::getExitCode() const
{
    return d->exitCode;
}
